[package]
name = "rustlib"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = "0.5.2"

[build-dependencies]
cc = "1.0"

[lib]
crate_type = ["staticlib", "dylib"]
